[common]
log_level = "info"

[network]

[network.groups.learned_session_20251127_050403]
hosts = [
  "www.goop.org",
]

[network.groups.learned_session_20251127_050431]
hosts = [
  "www.example.com",
]

[network.groups.learned_session_20251127_051819]
hosts = [
  "api.anthropic.com",
]

[network.groups.learned_session_20251127_051819]
hosts = [
  "statsig.anthropic.com",
]

